### ISSUE TITLE
diplay formatted  money from currency and amount 

### ISSUE THREAD

**Issue by devZakariya** [noojee/money.dart#10]
Hey 
please how can i diplay formatted  money from currency and amount 

```
final Currency usd = Currency.create('USD', 2);
String amount = "1500.0" 
print (res) // 1500.00 USD 
```

i want a fuction that can fill the res value

**Comment by devZakariya** [comment]
```
final Currency usd = Currency.create('USD', 2);
String amount = "1500.0" ;
String res = displayFormattedAmount(amount ,usd);
print (res) // 1500.00 USD 
```

**Comment by bsutton** [comment]
Sorry but I'm missed the notification on this one.

I'm not certain I understand your question.

print(amount.format('#.## CCC'));
-> 1500.00 USD

**Comment by bsutton** [comment]
If the above doesn't resolve you issue please feel free to re-open this issue.
