### ISSUE TITLE
Missing Symbol for Dollar Currencies

### ISSUE THREAD

**Issue by awhitford** [noojee/money.dart#11]
For the [Common Currencies](https://github.com/noojee/money.dart#common-currencies), the dollars do not have a `$` symbol.  _Why not?_
```dart
Currency usd = Currency.create('USD', 2);
// Australia
Currency aud = Currency.create('AUD', 2);
// New Zealand
Currency nzd = Currency.create('NZD', 2);
// Canada
Currency cad = Currency.create('CAD', 2);
```

**Comment by bsutton** [comment]
The method Currency.create defaults the symbol to '$'

Currency.create(this.code, this.minorDigits,
      {this.symbol = '\$',
      this.pattern = 'S0.00',
      this.invertSeparators = false})

**Comment by bsutton** [comment]
If the above answer doesn't resolve you issue please feel free to re-open the issue.
