### ISSUE TITLE
parse/toString issue with negative numbers

### ISSUE THREAD

**Issue by samandmoore** [noojee/money.dart#12]
Hi, thank you for this library.

I'm running into a surprising behavior and I wanted to report it and see if I'm doing something wrong or there's a bug.

I'm trying to convert a negative integer into a `Money` instance and print it as a `String`. 

Here's a test case:

```dart
test('it formats the value with the negative sign after the dollar sign', () {
  expect(Money.fromInt(-199, Currency.create('USD', 2)).toString(), '\$-1.99');
});
```

This test is failing for me with this error:

```
Expected: '$-1.99'
  Actual: '$-1.01'
   Which: is different.
          Expected: $-1.99
            Actual: $-1.01
                        ^
           Differ at offset 4
```

When I debug it, I'm seeing that the internal cents value is correctly, `-199`. 

Relatedly, when I try to parse a negative number using a string, I get a `MoneyFormatException`

```dart
test('it formats the value with the negative sign after the dollar sign', () {
  expect(Money.parse('\$-1.99', Currency.create('USD', 2)).toString(), '\$-1.99');
});
```

Any idea what's happening here?

Using `money2` version `1.4.0` and this version of flutter/dart:

```
[✓] Flutter (Channel unknown, 1.19.0-4.1.pre, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.19.0-4.1.pre at /Users/sammoore/flutter
    • Framework revision f994b76974 (5 weeks ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)
```

**Comment by bsutton** [comment]
Fixed in 1.4.2.
