### ISSUE TITLE
Is there a toInt method? 

### ISSUE THREAD

**Issue by Aynn** [noojee/money.dart#16]
Would be neat to be able to be able to pass a value and currency and get the appropriate Int value.

**Comment by bsutton** [comment]
I'm think that maybe it should be

Bigint get minorUnits;

Thoughts?

**Comment by bsutton** [comment]
Actually the method already exists!

Money.parse('10.00').minorUnits.toInt()  == 1000;

I'm not certain we benefit by having a specific 'toInt' method?
