### ISSUE TITLE
Wrong currency for Portuguese

### ISSUE THREAD

**Issue by erperejildo** [noojee/money.dart#18]
It's not taking €, it takes the Brazilian currency:
![Screenshot 2020-10-07 at 14 15 58](https://user-images.githubusercontent.com/5629919/95329705-affbaf80-08a7-11eb-9d60-690a2319946d.png)

You can see on the left that I send `pt`

**Comment by bsutton** [comment]
Sorry for the late reply.

I'm a little confused when you say we have the wrong currency as Portuguese isn't in the list of common currencies.

Do you mean that you would like the currency added to the list of common currencies?

If so the raise a PR and I will be happy to accept it.

**Comment by oscarfv** [comment]
Portuguese is a language, Portugal is a country. The currency depends on the country, `lang` just determines the language.

Apart from this, it is not clear to me what's wrong from your screenshot. Please describe a sequence of steps, stating what you see and what you were expecting to see instead.

**Comment by erperejildo** [comment]
> Portuguese is a language, Portugal is a country

Is it? No way!

Anyway... investigating this a bit further, there is nothing wrong related to this package, the problem comes more from Flutter itself. But TBH I don't really know if I should call it error.

For example if I do:
`String lang = Provider.of<MyRents>(context).language;`
I'd get Portuguese language as "pt". My understanding is that the main country should be Portugal, not Brazil, so this translates to Brazilian currency at the end.

I guess more than talking about an "error" here we should discuss what makes a country the main one for that language but that's a different topic.

I fixed it by having a currency selector in my app.
