### ISSUE TITLE
Money.parse(money.toString(), currency) fails when currency has a multi-char symbol

### ISSUE THREAD

**Issue by luistrivelatto** [noojee/money.dart#24]
It seems decode and encode are not inverse operations with currencies that have multi-char symbols. The following code:
```dart
void main() {
  var m1 = Money.from(0, CommonCurrencies().brl);
  var m2 = Money.parse(m1.toString(), CommonCurrencies().brl);
}
```
throws the following exception:
```
monetaryValue contained an unexpected character '$' at pos 1 
        when a match for pattern character S at pos 0 was expected.
```
Apparently, that's because brl has symbol "R$", and PatternDecoder compares a single char from the pattern expecting it to be equal to the currency's symbol. This problem also happens in other currencies with multi-char symbols like chf and nok.

**Comment by luistrivelatto** [comment]
Speaking of brl, the standard for Brazil is to invertSeparators. So a minor issue: brl should be defined as
```dart
Currency.create('BRL', 2, symbol: r'R$', pattern: 'S0,00', invertSeparators: true);
```

**Comment by bsutton** [comment]
So you are saying that the code is brl but the symbol is R$?

**Comment by bsutton** [comment]
So USD is written $USD10.00

Is the equivalent

$RBRL10,00

**Comment by luistrivelatto** [comment]
Sorry if I made myself unclear. The symbol and code for CommonCurrencies().brl are already correct, the issue is with the separator :) (and the .parse method, but that's a different story.)

In other words: BRL is the ISO code, and R$ is the every-day symbol. So these would be equivalent:
$10.00 => R$10,00  (notice the separator difference)
$1,000.00 => R$1.000,00
1 USD => 1 BRL

I'm not familiar with the [code][symbol] notation, I don't remember seeing it. But if the US dollars goes $USD10.00, then BRL should go R$BRL10,00.
