### ISSUE TITLE
Losing digits

### ISSUE THREAD

**Issue by yuriescl** [noojee/money.dart#29]
I'm using the following snippet:

```
Money sendAmount = Money.fromInt(123, Currency.create('CUR1', 2));
print('sendAmount: $sendAmount');
Currency receiveCurrency = Currency.create('EXC', 8);
Money exchangeRate = Money.fromInt(212345678, receiveCurrency);
print('exchangeRate: $exchangeRate');
Money receiveAmount = sendAmount.exchangeTo(exchangeRate);
print('receiveAmount: $receiveAmount');
Money exchangeTwoDigits = Money.fromInt(100, Currency.create('DST', 2));
Money receiveAmountTwoDigits = receiveAmount.exchangeTo(exchangeTwoDigits);
print('receiveAmountTwoDigits: $receiveAmountTwoDigits');
```

And getting this output:

```
I/flutter ( 7700): sendAmount: $1.23
I/flutter ( 7700): exchangeRate: $2.23
I/flutter ( 7700): receiveAmount: $2.11
I/flutter ( 7700): receiveAmountTwoDigits: $2611851.83
```

About the output:
- `sendAmount` is correct
- `exchangeRate` should be `2.12345678`
- `receiveAmount` should be `2.61185184` (`2.12345678×1.23 = 2.611851839`)
- `receiveAmountTwoDigits` should be `2.61` (`2.61185184` rounded to two digits)

Why are the outputs incorrect?

**Comment by bsutton** [comment]
I suspect this is a bug with the formatter.

I'm currently doing some work on the formatter and will add the above
examples as unit tests. The formatter needs a complete re-write as it's
handling of decimal places is just broken.

It's probably going to take me a couple of weeks to get to  the above work
so would welcome a PR in the meantime :)
