### ISSUE TITLE
Do not deprecate Money.fromBigInt

### ISSUE THREAD

**Issue by tlvenn** [noojee/money.dart#31]
Hi @bsutton,

I am already storing money values as `BigInt` or more precisely as observables of `BigInt` using mobx and would be interested to expose some computed values as `Money` however I want Money to be a simple box around my existing BigInt values.

The factory `Money.fromBigInt` just do that by passing the existing `BigInt` to the MinorUnit factory that uses the existing instance so that from an allocation memory perspective, there is only one `BigInt` representing that value in memory.

The more general factory `Money.from` will instantiate another `BigInt` ending with twice the memory allocation for each boxed values.

**Comment by bsutton** [comment]
Ok, I've reverted the deprecated in 2.0.2.

**Comment by bsutton** [comment]
sorry 2.0.3
