### ISSUE TITLE
Please add @Deprecated annotation for deprecated methods/variables

### ISSUE THREAD

**Issue by calvintam236** [noojee/money.dart#35]
Please add this to the package so the linter can show deprecated warnings.

Example: https://github.com/FilledStacks/stacked/blob/3a9293f8f06533eb7799c86d6267c78a960e0d6f/packages/stacked/lib/src/state_management/base_view_models.dart#L231

Ref: https://api.dart.dev/stable/2.13.3/dart-core/Deprecated-class.html

**Comment by bsutton** [comment]
Sorry I'm not certain what your asking here.

It's there a method that I've not marked as deprecated correctly?

I normally use @Deprecated and I've not had to do anything special in other
packages for the linter to provide warnings.

**Comment by bsutton** [comment]
Sorry I just checked the code and you are correct I had used @deprecated rather than @Deprecated.

I've just published 2.1.4 which fixes this issue.
