### ISSUE TITLE
conflicting documentation on Common Currencies list

### ISSUE THREAD

**Issue by calvintam236** [noojee/money.dart#36]
https://money2.noojee.dev/creating-a-currency says `The Money2 package does not contain a list of Common Currencies however you can also create your own.`,

but https://money2.noojee.dev/common-currencies says `From version 1.4.0 we ship with a list of common currencies.`.

This is conflicting. I believe the latter is correct?

**Comment by bsutton** [comment]
Thanks for spotting that.

I've updated the paragraph to reflect that we ship with common currencies and I've updated the documentation to reflect the current list that we support.

Much appreciated.
