### ISSUE TITLE
Best way to create a singleton service?

### ISSUE THREAD

**Issue by calvintam236** [noojee/money.dart#38]
I am writing a singleton stacked service (requires returning an instance), and I realize the package does not return a singleton instance that I can use?

https://github.com/noojee/money.dart/blob/de262f483b8b2293725781189d4b798663bd5c37/lib/src/common_currencies.dart#L97 does not return the `Currencies` instance.

https://github.com/noojee/money.dart/blob/de262f483b8b2293725781189d4b798663bd5c37/lib/src/currencies.dart#L51 does not as well. This should be preferred as we might add currencies that are not one of the common one and want to access them.

Note that rest of `Currencies` class other than `Currencies.parse` is also missing from the documentation.

Ref: https://pub.dev/packages/stacked

**Comment by bsutton** [comment]
All members of the Currencies class are static and as such essentially acts as a singleton.

I'm not certain the use of static was the best choice but I don't see what the benefit would be of changing it to a singleton?

I've just improved the gitbook documenation around the Currencies class but I'm uncertain which documentation you are referring to when you say:
   Note that rest of Currencies class other than Currencies.parse is also missing from the documentation.

Each method is documented (although I've just added some additional details) in the api doco?

**Comment by bsutton** [comment]
I've just published the documentation improvements.

**Comment by calvintam236** [comment]
> All members of the Currencies class are static and as such essentially acts as a singleton.
> 
> I'm not certain the use of static was the best choice but I don't see what the benefit would be of changing it to a singleton?

Right now, it is not returning an instance at all. That line is commented..

Dart now also recommends using `factory` constructor per [here](https://dart.dev/guides/language/language-tour#factory-constructors).

> I've just improved the gitbook documenation around the Currencies class but I'm uncertain which documentation you are referring to when you say:
> Note that rest of Currencies class other than Currencies.parse is also missing from the documentation.
> 
> Each method is documented (although I've just added some additional details) in the api doco?

There should be a dedicated section for `Currencies`. Search does nothing in the documentation.

**Comment by calvintam236** [comment]
https://dart.academy/creational-design-patterns-for-dart-and-flutter-singleton/

I think singleton is the right way because we do not want multiple instances of `Currencies`.

**Comment by bsutton** [comment]
Currencies documentation:
https://pub.dev/documentation/money2/latest/money2/Currencies-class.html

https://money2.noojee.dev/registering-a-currency

Currencies doesn't need to return an instance as it's static.

```dart
CommonCurrencies().registerAll();
// use default pattern registered with USD currency.
final usdAmount = Currencies.parse(r'$USD1500.0');
```
you can now access your registered currency anywhere in your code.

I do agree that a singleton would have been a better choice but changing it now is a breaking change so I would need a compelling reason to do so.

**Comment by bsutton** [comment]
A static does exactly that. As all members are static there can be only one
instant.
Using all statics is a singleton by any definition, except it uses a
different design pattern.

S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by calvintam236** [comment]
> I do agree that a singleton would have been a better choice but changing it now is a breaking change so I would need a compelling reason to do so.

You can read over this: https://volosoft.com/blog/Prefer-Singleton-Pattern-over-Static-Class

I think most of the packages I am using are using Singleton, e.g. official’s `shared_preferences`, `connectivity`, etc. I think most dart devs are more familiar with singleton now.
If some devs are using something like [`injectable`](https://pub.dev/packages/injectable), this has way better advantages: simplicity, lazy load.

You can publish a pre-release on pub.dev for people who want to start migrating over. Old version will always available for those are not ready to do so.

I’m using [`stacked`](https://pub.dev/packages/stacked), which is gaining popularity. With a singleton service, I only need to import the library once and able to use this service over the whole app without another import. No more messy imports! 👍 

Supporting singleton is just the best way forward. It will happen sooner than later.

**Comment by bsutton** [comment]
I think the most persuasive arguments are the ability to mock a singleton
and that google recommends using a factory.

I don't understand what you are saying regarding imports. Static or
singleton will not change how you import the library.

I can leave the static methods in place and mark them as deprecated and
have them just pass through calls to the singleton library.

I honestly don't think the change will have a material impact on how money
is used but sure.

S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by calvintam236** [comment]
> I don't understand what you are saying regarding imports. Static or singleton will not change how you import the library.

In `stacked` (M-V-VM architecture), when you make a library a service and add it to `@StackedApp` dependencies for lazy load, I can just use `locator<service name>` in viewmodel from `stacked` library (which you are already importing to use for other stacked stuff) when you need it. (Note that a service can depends on another service(s).)

Service in `stacked` is the actor dealing everything related to the library (only import library in this service file once among all files) and you can just ask it to do stuff from view (UI) side without needing to importing the library in the view. Hence, every files get shorter imports.

**Comment by bsutton** [comment]
The singleton version of Currencies will be released in 3.0.0

**Comment by calvintam236** [comment]
should `Money` always use with `Currencies`? if true, `Money.from()` can accept code instead of `Currency`.

**Comment by bsutton** [comment]
What do you think of the idea of pre-registering all of the common currencies?

**Comment by bsutton** [comment]
If we did this, then I think there is a valid argument for changing all of the methods to take a code rather than a currency.

The issue would be if someone wanted an odd currency for a special use case.
To facilitate this would could do:

```
Money.from(num amount, string code)
Money.fromCurrency(num amount, Currency currency)
``
This would need to be replicated for each of:
```
Money.fromBigInt
Money.fromInt
Money.parse
Money.fromString
```

I don't love my suggested naming conventions.

**Comment by bsutton** [comment]
Maybe:
```
oney.from(num amount, string code)
Money.fromWithCurrency(num amount, Currency currency)

Money.fromBigInt
Money.fromBigIntWithCurrency(

Money.fromIntWithCurrency(
or
Money.fromIntUsingCurrency(

```
other ideas?
preferences?

**Comment by calvintam236** [comment]
> What do you think of the idea of pre-registering all of the common currencies?

i would prefer that but user should able to overwrite common currencies for their customized currency.

**Comment by bsutton** [comment]
The Currencies.register method already lets you replace an currency, so this should work fine.

What about the naming conventions as above?

**Comment by calvintam236** [comment]
> Maybe:
> 
> ```
> oney.from(num amount, string code)
> Money.fromWithCurrency(num amount, Currency currency)
> 
> Money.fromBigInt
> Money.fromBigIntWithCurrency(
> 
> Money.fromIntWithCurrency(
> or
> Money.fromIntUsingCurrency(
> ```
> 
> other ideas?
> preferences?

maybe you can take `<T>` e.g. `Money<T>.from()`
T can be `int` or `Currency`

**Comment by bsutton** [comment]
Also what would it mean if you passed a type other than a String or Currency?

**Comment by bsutton** [comment]
This does feel like a mis-use of generic types.

**Comment by calvintam236** [comment]
> Maybe:
> 
> ```
> oney.from(num amount, string code)
> Money.fromWithCurrency(num amount, Currency currency)
> 
> Money.fromBigInt
> Money.fromBigIntWithCurrency(
> 
> Money.fromIntWithCurrency(
> or
> Money.fromIntUsingCurrency(
> 
> Money.parse(String monetaryAmount, {required String code,
>       String? pattern})
> Money.parse(String monetaryAmount, Currency currency,
>       {String? pattern})
> ```
> 
> other ideas?
> preferences?

the other option is to accept dynamic type for the second parameter and throw exception if it is not one of currency code or it is not currency. i don’t think we should adding more methods (name with different variations)

**Comment by calvintam236** [comment]
> > Maybe:
> > ```
> > oney.from(num amount, string code)
> > Money.fromWithCurrency(num amount, Currency currency)
> > 
> > Money.fromBigInt
> > Money.fromBigIntWithCurrency(
> > 
> > Money.fromIntWithCurrency(
> > or
> > Money.fromIntUsingCurrency(
> > 
> > Money.parse(String monetaryAmount, {required String code,
> >       String? pattern})
> > Money.parse(String monetaryAmount, Currency currency,
> >       {String? pattern})
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > other ideas?
> > preferences?
> 
> the other option is to accept dynamic type for the second parameter and throw exception if it is not one of currency code or it is not currency. i don’t think we should adding more methods (name with different variations)

alternatively, it can use optional parameter and if both null throw an exception.

**Comment by bsutton** [comment]
I would not support using dynamic.
You have just moved what should be a compiler error to a runtime error. This is always a mistake.

I think you have been writing too much javascript :)

**Comment by bsutton** [comment]
the optional params have the same problem, again you have moved what should be a compiler error to a runtime error.

**Comment by calvintam236** [comment]
normally, function overloading is the way. dart does not support it. there is no native union type either.

maybe `MoneyWithCurrency` and wrapping the methods (basically factory a Money instance and pass the currency code)?

**Comment by bsutton** [comment]
I've published a second beta.
It now pre-registers all common currencies and the Money methods no take a code.

For the moment I've used the Money.parseWithCurrency variant to support passing an unregistered code.

Take it for a spin and let me know what problems it causes.

**Comment by bsutton** [comment]
3.0.0-beta.2

**Comment by calvintam236** [comment]
1. is the currency code case sensitive? The code param should be case insensitive (`.toUpperCase()`).
2. `Currencies.find()` can alias to `operator[]`. `.register()` can alias to `operator[]=`.

**Comment by calvintam236** [comment]
https://github.com/noojee/money.dart/blob/27e016cfb85173114711158841607d96cf2e7139/lib/src/money.dart#L416
3. shouldn’t this throw `CurrencyNotFoundException` if that code is not found?

https://github.com/noojee/money.dart/blob/27e016cfb85173114711158841607d96cf2e7139/lib/src/money.dart#L566
4. we -> if?

https://github.com/noojee/money.dart/blob/27e016cfb85173114711158841607d96cf2e7139/lib/src/currencies.dart#L25
https://github.com/noojee/money.dart/blob/27e016cfb85173114711158841607d96cf2e7139/lib/src/money.dart#L28
5. these should be relative path?

https://github.com/noojee/money.dart/blob/27e016cfb85173114711158841607d96cf2e7139/lib/src/common_currencies.dart#L1
6. this should import `money.dart`?

**Comment by bsutton** [comment]
>     1. is the currency code case sensitive? The code param should be case insensitive (`.toUpperCase()`).
> 
>     2. `Currencies.find()` can alias to `operator[]`. `.register()` can alias to `operator[]=`.

Currency codes must be upper case.  

Do the operator overloads make the code cleaner to use?

**Comment by calvintam236** [comment]
> Currency codes must be upper case.

https://github.com/noojee/money.dart/blob/27e016cfb85173114711158841607d96cf2e7139/lib/src/currency.dart#L93-L103

There is no check for case of the code when it is created.

> Do the operator overloads make the code cleaner to use?

Yes, e.g. `Currencies.register(Currency.create(XXX))` -> `Currencies[XXX] = Currency.create()`

**Comment by bsutton** [comment]
I should have not correctly said they are case sensitive.

Some sub currencies contain lower case letters.

They main currencies are all upper case.

**Comment by bsutton** [comment]
The design intent of isInCurrency is to return false if its not found. Exceptions should normally only be thrown in 'exceptional' circumstances.  The code not existing is one of the expected outcomes.

> 3. shouldn’t this throw `CurrencyNotFoundException` if that code is not found?
> https://github.com/noojee/money.dart/blob/27e016cfb85173114711158841607d96cf2e7139/lib/src/money.dart#L566
> 
> 

Sorry but I don't understand what you are asking here.

> 4. we -> if?
> https://github.com/noojee/money.dart/blob/27e016cfb85173114711158841607d96cf2e7139/lib/src/currencies.dart#L25
> 
>

I'm going to turn the linting up and change everything to relative paths. 
> https://github.com/noojee/money.dart/blob/27e016cfb85173114711158841607d96cf2e7139/lib/src/money.dart#L28
> 
> 
> 5. these should be relative path?
> https://github.com/noojee/money.dart/blob/27e016cfb85173114711158841607d96cf2e7139/lib/src/common_currencies.dart#L1
> 
> 
> 6. this should import `money.dart`?

**Comment by calvintam236** [comment]
> The design intent of isInCurrency is to return false if its not found. Exceptions should normally only be thrown in 'exceptional' circumstances. The code not existing is one of the expected outcomes.
> 
> > 1. shouldn’t this throw `CurrencyNotFoundException` if that code is not found?
> >    https://github.com/noojee/money.dart/blob/27e016cfb85173114711158841607d96cf2e7139/lib/src/money.dart#L566
> 
> Sorry but I don't understand what you are asking here.
> 
> > 1. we -> if?
> >    https://github.com/noojee/money.dart/blob/27e016cfb85173114711158841607d96cf2e7139/lib/src/currencies.dart#L25
> 
> I'm going to turn the linting up and change everything to relative paths.
> 
> > https://github.com/noojee/money.dart/blob/27e016cfb85173114711158841607d96cf2e7139/lib/src/money.dart#L28
> > 
> > 
> > 1. these should be relative path?
> >    https://github.com/noojee/money.dart/blob/27e016cfb85173114711158841607d96cf2e7139/lib/src/common_currencies.dart#L1
> > 2. this should import `money.dart`?

I think you are reading the code snippet wrong. Code snippets are before my comment.

**Comment by bsutton** [comment]
Can you elaborate on 3. and 4. as I don't understand what you are asking. Your comments are a little terse :)

**Comment by calvintam236** [comment]
> https://github.com/noojee/money.dart/blob/27e016cfb85173114711158841607d96cf2e7139/lib/src/money.dart#L566
> 
> 
> 4. we -> if?

maybe it should be when??

**Comment by bsutton** [comment]
fixed.
S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by bsutton** [comment]
Each of the Money ctors now have two versions  one that takes a currency code and one that  takes a currency.

I think this should satisfy most use cases.

I'm closing out but if you disagree feel free to reopen.
