### ISSUE TITLE
Thousand separator

### ISSUE THREAD

**Issue by kephren226** [noojee/money.dart#39]
Is there a way to use space as thousand separatror 
Trying to do it without success

**Comment by bsutton** [comment]
No.

**Comment by bsutton** [comment]
Hmm. Have you tried setting the decimalSeparator in the currency vote?

**Comment by kephren226** [comment]
> Hmm. Have you tried setting the decimalSeparator in the currency ctor?

How should i do it?
Extend the class and override the constuctor ?

**Comment by kephren226** [comment]
Actually i found a solution not the best one but it work 
I just replace the thousant separation in the result with space usung replaceAll

**Comment by bsutton** [comment]
I'm going to close this as I don't think it is a common use case and there is a work around (e.g. use replaceAll).

if we get more enquires for a similar feature will consider it then.
