### ISSUE TITLE
money values with single digit cents do not format correctly

### ISSUE THREAD

**Issue by oysterpack** [noojee/money.dart#4]
The following test replicates the issue:

```dart
test('Money formatting 301 bug', () {
    expect(Money.fromInt(301, Currency.create('USD', 2)).toString(), '\$3.01');
});
```
Any minor unit that is single digit. In the above example, 301 gets formatted as $3.10 instead of $3.01.

The problem is caused by https://github.com/noojee/money.dart/blob/master/lib/src/pattern_encoder.dart :
```dart
// Fixed problems caused by passing a int to the NumberFormat when we are trying to format a decimal.
// Move leading zeros to the end.
formatted = invertZeros(formatted);
// Add trailing zeros.
```

**Comment by bsutton** [comment]
Are you happy to have a go a fixing this?

**Comment by oysterpack** [comment]
yep - working on it ...

**Comment by bsutton** [comment]
FYI, I've just published a new version including your fixes.

New version is 1.3.0.
