### ISSUE TITLE
`operator==` not checking for same reference or runtimeType

### ISSUE THREAD

**Issue by calvintam236** [noojee/money.dart#40]
https://github.com/noojee/money.dart/blob/09b1e859d4f6cc78ba181dd4536521cfe8e389e7/lib/src/currency.dart#L155

This should also use [`identical()`](https://api.dart.dev/stable/2.13.4/dart-core/identical.html) from `dart:core` to check for reference. `.runtimeType` should be checked as well.

good example from [here](https://pub.dev/packages/equatable)
```dart
class Person {
  const Person(this.name);

  final String name;

  @override
  bool operator ==(Object other) =>
    identical(this, other) ||
    other is Person &&
    runtimeType == other.runtimeType &&
    name == other.name;

  @override
  int get hashCode => name.hashCode;
}
```

**Comment by bsutton** [comment]
Sounds reasonable.

Would you be able to submit a pr with there change.

**Comment by bsutton** [comment]
Just a thought.

Shouldn't we be passing a Person as other and use covariant which would
remove the need for the type check.

**Comment by calvintam236** [comment]
> Just a thought. Shouldn't we be passing a Person as other and use covariant which would remove the need for the type check.
> […](#)

If it is not a `Object`, it will throw `Exception`. The `operator==` should be able to check that in runtime.

**Comment by bsutton** [comment]
If we use covariant we should get a complie time error which is better than
a runtime error.

**Comment by calvintam236** [comment]
> If we use covariant we should get a complie time error which is better than a runtime error.
> […](#)

If the `Money` was generated in runtime from API and such, it will cause fatal error to user in the UI and requires `try…catch`. That’s why it should be `Object` and return `bool` because this method is not changing any data.

**Comment by bsutton** [comment]
Can you provide more detail on your runtime scenario.
If a user enters a monetary amount from the UI I would expect to see code
something like:

var userMoneyValue = '$10.00"; // user enters this value from the ui.
var money = Money.parse(userMoneyValue);
if (money == Money.fromInt(1000))
{

}

The parse can generate an exception but I can't think of a common path that
would result in the == operator causing a problem.


S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by calvintam236** [comment]
> Can you provide more detail on your runtime scenario. If a user enters a monetary amount from the UI I would expect to see code something like: var userMoneyValue = '$10.00"; // user enters this value from the ui. var money = Money.parse(userMoneyValue); if (money == Money.fromInt(1000)) { } The parse can generate an exception but I can't think of a common path that would result in the == operator causing a problem. S. Brett Sutton Noojee Contact Solutions 03 8320 8100
> […](#)


https://github.com/dart-lang/sdk/blob/master/sdk/lib/core/object.dart#L52
They use `Object other`.

```dart
Money m1 = Money.fromInt(1000);
dynamic m2 = 1000; // this can be any type and set at runtime. some may use var
if (m1 == m2)
// throw exception in UI end and requires try catch
```

**Comment by bsutton** [comment]
The answer to that one is simple.

Don't use dynamic, its bad practice.

It will also give a compile error:

```

test('equality', () {

Money m1 = Money.fromInt(1000, usd);

dynamic m2 = 1000; // this can be any type and set at runtime. some may use
var

if (m1 == m2)

});

```

Yields the following error:
"The argument type 'dynamic' can't be assigned to the parameter type
'Money?'.",

Under what circumstance would you even consider using dynamic.
If a user is entering a money amount then you know its a monetary amount so
why would you put it into a dynamic.


S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by bsutton** [comment]
I've rewritten money == as:

```
  @override
  bool operator ==(covariant Money other) =>
      identical(this, other) || (
      isInSameCurrencyAs(other) &&
      other._minorUnits == _minorUnits);
```

and Currency == as
```

  @override
  bool operator ==(covariant Currency other) =>
      identical(this, other) ||
      (other is Currency && code == other.code && precision == other.precision);
```

MinorUnits

```
  @override
  bool operator ==(covariant MinorUnits other) =>
      identical(this, other) || (other is MinorUnits && _value == other._value);
```

This removes the need for the runtime checks and makes the errors compile time errors.

**Comment by bsutton** [comment]
If you want to stay with passing dynamic you need to provide a more convincing argument as to why it's necessary.

Moving to a compile time error helps everyone.

**Comment by calvintam236** [comment]
> If you want to stay with passing dynamic you need to provide a more convincing argument as to why it's necessary.
> 
> Moving to a compile time error helps everyone.

Most dart native libraries are using `(Object other)`.
if you are using different approach, make sure you document that since no one would expect it will not accept non-`Money` type.

https://api.dart.dev/stable/2.0.0/dart-core/num/operator_equals.html

**Comment by bsutton** [comment]
the link specifically is for the num type.

I don't think it needs to be documented as you now get a compiler error.

I have pushed a 3.0.0-beta-1 with the operator changes and the singleton currencies.

Take it for a spin and lets see if it causes any problems.

**Comment by calvintam236** [comment]
https://github.com/noojee/money.dart/runs/3083083713?check_suite_focus=true

test has failed.

**Comment by bsutton** [comment]
It's some sort of issue with the CI configuration.
The unit tests actually all pass.
If you look at the error its complaining about an issue in the meta library

S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by calvintam236** [comment]
> the link specifically is for the num type.
> 
> I don't think it needs to be documented as you now get a compiler error.
> 
> I have pushed a 3.0.0-beta-1 with the operator changes and the singleton currencies.
> 
> Take it for a spin and lets see if it causes any problems.

Regarding throwing exception, read this:
http://github.com/dart-lang/sdk/blob/master/sdk/lib/core/object.dart#L36
This should include compile time and runtime?

- https://api.dart.dev/stable/2.13.4/dart-mirrors/InstanceMirror/operator_equals.html
- https://api.dart.dev/stable/2.13.4/dart-math/Rectangle/operator_equals.html
- https://api.dart.dev/stable/2.13.4/dart-core/List/operator_equals.html

and there are more. Just random pick from the search.

`Object other` is used by most of dart native classes as they are inheriting from `Object`‘s `operator ==`.

https://github.com/dart-lang/sdk/blob/master/sdk/lib/core/object.dart#L27-L52

**Comment by bsutton** [comment]
None of the operator == implementations that I've released throw rather they will generate compile time errors.

Whilst I take your point that existing implementations don't use covariant I suspect that this is because they were implemented before covariant was part of the language specification.

I also don't believe that using a covariant breaks the rules.

The bottom line is that I can't see any down side to using covariant and there is clear up side to using it.
I would need to see a real world example that using covariant was detrimental to consider reverting it.

**Comment by bsutton** [comment]
I've pushed beta.3 which has the [] operators and cleanup of the packages.

I don't think I will have time to play with the Codec concept at this point. If you want push a PR it seams like a reasonable idea.

**Comment by calvintam236** [comment]
> None of the operator == implementations that I've released throw rather they will generate compile time errors.
> 
> Whilst I take your point that existing implementations don't use covariant I suspect that this is because they were implemented before covariant was part of the language specification.
> 
> I also don't believe that using a covariant breaks the rules.
> 
> The bottom line is that I can't see any down side to using covariant and there is clear up side to using it.
> I would need to see a real world example that using covariant was detrimental to consider reverting it.

https://github.com/dart-lang/language/issues/949

Just a read-up from Dart if you are interested.

**Comment by bsutton** [comment]
Closing this as it looks like the Dart team had the same conversation we did and decided to allow covariant.
Only down side is that you can put a Money into a map of other objects. But then you just shouldn't be doing that anyway.
