### ISSUE TITLE
Better way to set exchange rate?

### ISSUE THREAD

**Issue by calvintam236** [noojee/money.dart#41]
I am on a project that has to handle multiple currencies conversion.

Per [here](https://money2.noojee.dev/exchange-rates), we have to create a different `Money` instance for each exchange rate.

Instead of doing it individually, is it possible to let `Currencies` to store the exchange rate with a method to set such value e.g. `.setExchangeRate(code1, code2, rate)` or a `List` for bulk, and able to exchange to desired currency code doing like this: `Money instance.exchangeTo(code)`?

**Comment by bsutton** [comment]
If you were going to do it I think I would prefer to see the api as:

```
Currencies.setExchangeRate(from: code1, to: code1, rate);

Having set the exchange rate the exchangeTo method should work in both directions.

e.g.

Currencies.setExchangeRate(from: 'AUD', to: 'USD', rate);

var aud = Money.parse('AUD10.00');
aud.exchangeTo('USD');

var usd = Money.parse('USD10.00');

usd.exchangeTo('AUD');
```

This does raise a couple of questions.

Should we pass a Currency rather than a currency code?

We can't use the exchangeTo method as that is already used.

So maybe:
```
aud.exchangeToByCode('USD');
or
aud.exchangeToCode('USD');

or
aud.convertTo('USD');

or
aud.exchangeWith('USD');
or
some better suggestion.
```

If an exchange rate hasn't been set then I think  it should throw a CurrencyExchangeException.

**Comment by calvintam236** [comment]
I think if currency code is unique, code is always easier for everyone. otherwise, you have to do this: `.exchangeTo(Currencies.find(XXX))` (since my database only store currency code).

**Comment by bsutton** [comment]
I think you are right.

**Comment by calvintam236** [comment]
I have added some code for this idea on #46.

**Comment by bsutton** [comment]
The exchangeTo method now takes a Fixed.

This provides a much cleaner interface and removes the confusion of using a Money to hold a scalar value.
