### ISSUE TITLE
Use `Codec` design over `MoneyEncoder` and `MoneyDecoder`?

### ISSUE THREAD

**Issue by calvintam236** [noojee/money.dart#42]
Just an idea here: use [`Codec`](https://api.dart.cn/stable/2.12.4/dart-convert/Codec-class.html) design from `dart:convert`

This allows combining `MoneyEncoder` and `MoneyDecoder` into one class `MoneyCodec` with flexibility to extends from it.

**Comment by bsutton** [comment]
I'm going to close this issue as at this point I'm not certain I can see any advantage of doing this.
I'm not even certain we get an advantage from using MoneyEncoder/Decoder as these don't look like useful extension points.
