### ISSUE TITLE
Upgrading to 3.0.0-beta.3 fails because of dependency version conflict on flutter_test

### ISSUE THREAD

**Issue by oysterpack** [noojee/money.dart#47]
`Because every version of flutter_test from sdk depends on meta 1.3.0 and money2 >=3.0.0-beta.3 depends on meta ^1.7.0, flutter_test from sdk is incompatible with money2 >=3.0.0-beta.3.`

I am using: Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)

**Comment by bsutton** [comment]
will be reverted to meta 1.3 in beta.4

**Comment by bsutton** [comment]
I've just published beta.4 with a fix for this.
