### ISSUE TITLE
Change MinorUnits to a FixedPrecision class

### ISSUE THREAD

**Issue by bsutton** [noojee/money.dart#48]
During discussion on setting exchange rates it has become apparently that we need a method of storing fixed precision no.

It has also highlighted discrepancies between the Money and Currency parse methods and the general set of constructors available to each.

Exchange rates are essentially fixed precision numbers.
The Money class is also a fixed precision value but with the addition of a Currency.

The MinorUnits class can store a large integer value but has no concept of precision.

I'm suggesting that we change MinorUnits to a Fixed Precision class.
Possible names are:
Fixed
FixedPrecision

The fixed precisions class would be of the form:

```dart
class Fixed {
MinorUnits units;
int precisions;
int _precisionFactor;

Fixed.parse(String amount, { String pattern = '#.#',  int precision, bool invertSeparators});
Fixed.from(num amount, int precision);
Fixed.fromInt(int amount, 
Fixed.fromBigInt(BigInt

/// mathematical operations
/// all the maths operators from MinorUnits

```

The 'invertSeparators' needs more discussion.  Is it required? If the user comes from a background where separators are inverted then they are likely to store rates in their db using inverted. The invertSeparators argument allows them to read
them directly from the db into a Fixed class without having to manipulate strings.

We would create Pattern encoders/decoders for the Fixed class.

Once we have a Fixed class the following changes would occur.

MinorUnits would no longer exist.

The Money class would store its minor units in a Fixed class using the precision from the Currency.
We would add a new constructor to Money that took a Fixed class - what happens if the precision is different - I think we should probably throw an exception.

Users would be encouraged to store their exchange rates in an instance of the Fixed class with the advantages of fixed precision mathematical operations.

(I wonder if we should release Fixed as a separate dart package as it could well be useful as a standalone package).

When registering an exchange rate a Fixed instance would be required:

```dart
var rate = Fixed.parse('0.11', precision: 4, pattern = "#.#', );

var inverseRate = Fixed.parse('1.1', precision: 4, pattern = "#,#', invertSeparators: true);

Currencies().registerExchangeRate(ExchangeRate(from: CommonCurrences.usd, to: CommonCurrencies.aud, rate: rate, inverseRate: inverseRate);
```
If the users are already storing their exchange rates using the Fixed class then requiring them to use a Fixed class when creating  an ExchangeRate will not be a burden.
It also means the method signature of registerExchangeRate is simplified as we don't have to deal with all the different ways a rate can be stored (string, int, double ...).

**Comment by calvintam236** [comment]
1. should `Fixed` handle parsing pattern? As it is a type, i think parsing functionality should be added to `Money` and `Currency` via mixin?
2. right now it is using `bigint` to store the value. @bsutton mentions that monetary value should never need more than 64bits, maybe we should use extends the `fixnum` type? (dart official package)
3. pattern encoders and decoders should use #42 approach?
4. is it possible to let `Money` constructor to build the instance of `Fixed` by passing same parameters needed. e.g. `Money.fixed(same param of Fixed(), currency code)`? it looks cleaner in code and do not require nesting constructor inside constructor

**Comment by calvintam236** [comment]
just checking API of `fixnum` and found out it has `intx` type. maybe this is what @bsutton looking for?

https://pub.dev/documentation/fixnum/latest/fixnum/IntX-class.html

**Comment by bsutton** [comment]
1) the parsing is currently handled by the PatternEncoder/Decoder for
money/currency. What would be the advantage of changing this to a mixin?
The #42 Codec approach internally with the existing interface feels more
appropriate.
I think the Fixed class needs its own parser as its parsing no.s no
currencies. It would be nice if it still supported parsing no.s with
thousand separators
2) I would suggest that we use rather than extend the general trend is to
move away from inheritance unless it truly is. In this case fixednum has a
number of operatoraters that I don't think we should expose (e.g. shift
left) and there is possibly an argument that a Fixed precisions no. isn't a
fixednum so inheritance is misinformed.
3) I would agree with the #42 approach
4) Fixed is not a currency so it won't be able to parse currency symbols
nor codes so I don't think this approach will work.
S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by bsutton** [comment]
intx is a fixed precision integer whilst we are looking to build a fixed
precisions decimal.

This might be an option:
https://pub.dev/packages/decimal

S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by bsutton** [comment]
Obvious problem withe Decimal class is that it doesn't allow you to set the
precision. It takes the precision from the parsed value which isn't what we
want.

We could submit PR or fork the project.

S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by calvintam236** [comment]
https://pub.dev/documentation/quantity/latest/number/Precise-class.html

maybe this is a better fit?

**Comment by bsutton** [comment]
> https://pub.dev/documentation/quantity/latest/number/Precise-class.html
> 
> maybe this is a better fit?

It won't allow us to support parsing european numbers '100.000,00' as it expects the decimal separator to be a period '.'.

**Comment by calvintam236** [comment]
> > https://pub.dev/documentation/quantity/latest/number/Precise-class.html
> > maybe this is a better fit?
> 
> It won't allow us to support parsing european numbers '100.000,00' as it expects the decimal separator to be a period '.'.

How about replacing `,` to empty string before passing to `Precise` constructor and add back `,` on `.toString()`? This job can be added to `Money`.

**Comment by bsutton** [comment]
> It won't allow us to support parsing european numbers '100.000,00' as it expects the decimal separator to be a period '.'.

Having said that and checking the code we do currently use NumberFormat and we switch the separators before calling it as it also doesn't deal with inverted separators.

I have intentionally tried to stay away from using locales as I've found them unreliable in other languages. I've not enough experience with Dart to know if it shares the same problem.

The Decimal class would require a number of enhancements and there is uncertainty as to whether changes would be accepted.
The Decimal class also uses locales for formating (as opposed to parsing for which there are no options) and as such they may be opposed to our 'roll your own' approach.
I will raise an issue on the Decimal git project to see what the reaction is.

**Comment by bsutton** [comment]
If we do roll our own we should look a the [rational](https://pub.dev/packages/rational) package which Decimal relies on.

**Comment by calvintam236** [comment]
@bsutton have you check out the reply at https://github.com/a14n/dart-decimal/issues/51?

**Comment by bsutton** [comment]
Work on a Fixed class is now complete. The Fixed class utilised the Decimal package under the hood.

We get a loss of performance but its a lot less work to implement and in most cases performance isn't going to be a concern.
If it turns out it is we can look going back to a singular bigint as the underlying storage.
