### ISSUE TITLE
Review constructors on the Money class

### ISSUE THREAD

**Issue by bsutton** [noojee/money.dart#49]
The money class currently has less constructors than the Currency class.

Review the set of ctors as I think the Money class should have the same constructors.

**Comment by pryshrm** [comment]
Please provide a constructor that uses Decimal .

**Comment by bsutton** [comment]
Will do. 
Look out for the next beta, I will try to include it.

**Comment by bsutton** [comment]
I should say that the intent with Money is to encourage the use of the Fixed package as it was designed specifically for use with Money2.

**Comment by bsutton** [comment]
Money now has lots of ctors.

We however need to review the use of positional vs named args, do we use a mix, only fixed or only named?

**Comment by bsutton** [comment]
We now have lots of ctors including a decimal one.
