### ISSUE TITLE
What is the pattern for INR(Indian Rupees)?

### ISSUE THREAD

**Issue by VengaiMovan** [noojee/money.dart#50]
Hi,
I want to convert an integer to INR format, I don't know the pattern format. Can u please tell me the pattern for INR?

**Comment by bsutton** [comment]
Look in the CommonCurrencies class.

**Comment by VengaiMovan** [comment]
Hi @bsutton ,
I tried that way but it didn't work, I have added the code and the output.
Thank You.

Code
`final Currency inr = Currency.create('INR', 2, symbol: '₹', invertSeparators: false, pattern: 'S000.00,00');
totLoss = jsonResponse['totLoss'].toString(); // return 73274
totLoss = Money.fromInt(int.parse(totLoss), inr).toString();
output :  ₹732.1,740
`

**Comment by bsutton** [comment]
So clearly a bug.

I did have on my to-do list to check out the inr. It is the only currency
that groups thousands left to right.

It will be a few days before I can look at this.
You welcomed to have a crack at fixing.

**Comment by bsutton** [comment]
I've just published v3 beta 5 which side steps this issue.

The CommonCurrencies for inr included thousand separators which no other currency does.
So I've removed the thousands separator and now the default format works.

This however doesn't fix the core bug where the formatter isn't working for left to right thousand separtors.

**Comment by bsutton** [comment]
I just noted that your pattern is wrong:

```
final Currency inr = Currency.create('INR', 2, symbol: '₹', invertSeparators: false, pattern: 'S000.00,00');
```
as invertSeparator is false the , and . a backward.

```
final Currency inr = Currency.create('INR', 2, symbol: '₹', invertSeparators: false, pattern: 'S000,00.00');
```
The common currency format is also wrong. I will push another beta that fixes this.

**Comment by bsutton** [comment]
I've must pushed beta 6 with the invertseparator fixed.

If you have the pattern correct looks like it actually works:

```
  expect(
          Currencies()
              .find('INR')!
              .copyWith(pattern: r'S##,##,###.##')
              .parse(r'₹1234567.89')
              .toString(),
          equals(r'₹12,34,567.89'));

    });
```
So I believe beta 6 fixes this.

I will close this, but if you have additional issues feel free to reopen.

**Comment by VengaiMovan** [comment]
Ok, @bsutton  thank you soo much, I'll try and report if anything wrong.
