### ISSUE TITLE
No support for Decimal

### ISSUE THREAD

**Issue by pryshrm** [noojee/money.dart#54]
I am trying to find out what is the recommended data type to use for monetary values and it seems Decimal from the decimal package is the way to go and using double is an absolute no no.

But I am surprised to find out that money2 does not provide any way out of the box to use Decimal. It accepts a double but not Decimal.  I was expecting a from method or a constructor that take a Decimal but there is none. I find that very weird. What am I missing?

**Comment by bsutton** [comment]
I'm currently working on the next beta release of money and I've introduced a new package 'fixed'.

Fixed has some similarities to decimal but it allows you to control the scale (no. of decimals) explicitly.
It also has a built in parser/formatter which is based of the Money2 parser/formatter for consistency.

https://pub.dev/packages/fixed

v3 of the money package has a new ctor (along with other changes).

Money.fromFixed(Fixed amount, {required String code})

**Comment by a14n** [comment]
I think that the main question is to have a `Money.fromDecimal(Decimal amount, {required String code})`.

Side question: wouldn't it make sense to base fixed on decimal? IIUC `Fixed` could simply be a wrapper of a `Decimal` value and a retained `scale`. One could also argument that `Money` could be enough and wrap the Decimal value, the scale and the currency. I'll be happy to help if you take that way :) .

**Comment by bsutton** [comment]
The fixed package is now implemented on top of Decimal and provides a constructor Fixed.fromDecimal.

I've also added a new Money ctor- Money.fromDecimal.

**Comment by bsutton** [comment]
@pryshrm @a14n 

Just checking that you saw that I've published a release candidate for both Money2 and Fixed.

Subject to any issues being identified I'm looking to publish these as releases at the end of the week.

**Comment by a14n** [comment]
I'm working on a new major release of Decimal/Rational that will contain some breaking changes. I hope to release an RC soon.

**Comment by bsutton** [comment]
Ok thanks for the heads up.
