### ISSUE TITLE
Currency exchange accuracy

### ISSUE THREAD

**Issue by kvadrakot** [noojee/money.dart#58]
Maybe I didn't understand something. Let's say the exchange rate is 0.013445 and amount 28000,  using clean code we get 

 var result = 28000 * 0.013445; 
 // = 376.46000000000004

 //using Money2
 Money price = Money.from(28000, code: 'RUB');
 Money rubToUsExchangeRate = Money.from(0.013445, code: "USD");
 var result = proce.exchangeTo(rubToUsExchangeRate).format('###,###.## S');
//= 280.00 $

**Comment by bsutton** [comment]
@kvadrakot 
Can I get you to try the published 3.x beta.
This will become the stable release at the end of the week.

How we do exchange rates has changed significantly.

We have a new package Fixed which stores fixed scale decimals.

In v3 the code is:
```dart
 test('rub', () {
      final price = Money.fromNum(28000, code: 'RUB');
      final rubToUsExchangeRate = ExchangeRate.fromNum(0.013445,
          scale: 6, fromCode: 'RUB', toCode: 'USD');
      expect(price.exchangeTo(rubToUsExchangeRate).format('###,###.## S'),
          equals(r'376.46 $'));
    });
```

**Comment by kvadrakot** [comment]
Thanks a lot for your help, I will use the new version 3.x beta.

**Comment by bsutton** [comment]
closing as I believe this is resolved in 3.x
