### ISSUE TITLE
Get format by country

### ISSUE THREAD

**Issue by erperejildo** [noojee/money.dart#6]
How can I detect that I need $34 or 34$ (US/Canada) based on country?

**Comment by awhitford** [comment]
Who says 34$? 🤔

**Comment by bsutton** [comment]
Using a trailing $ is unusual but does happen occasionally for formatting.
In that case you need to provide your own pattern when formatting.
Unless you are familiar with what you users want I would always use the $34 version.

**Comment by erperejildo** [comment]
> Who says 34$? 🤔

> Using a trailing $ is unusual but does happen occasionally for formatting.
> In that case you need to provide your own pattern when formatting.
> Unless you are familiar with what you users want I would always use the $34 version.

For € is common to have X€ format and still displaying €X.

Spain: https://www.pccomponentes.com/
France: https://www.materiel.net/carte-graphique/l426/
Germany: https://www.caseking.de/pc-komponenten/cpus-prozessoren/intel
etc

**Comment by bsutton** [comment]
The formatters and parsers allow you to choose whatever order you wish.
