### ISSUE TITLE
Scale zero works bad when multiplying

### ISSUE THREAD

**Issue by oakstair** [noojee/money.dart#60]
I tried to multiply a Money instance with a double value but this didn't work so well.

Currencies().register(Currency.create('SEK', 0, symbol: 'kr', pattern: '0 S'));
final Money hundraSEK = Money.fromInt(100, code: 'SEK');
// expect((hundraSEK * 0.5).toString(), '50 kr');  // Does not work since we have a zero scale. 0.5 get converted into Fixed 1.

**Comment by bsutton** [comment]
The question is whether this is a bug or are you using the library incorrectly.

The question is what scale do we use?

With a double there is no easy to determine the expected scale.

So the correct solution feels like you should convert the double to a fixed and then do then the maths


Thoughts?

**Comment by oakstair** [comment]
?The question is what scale do we use?
I use scale 0 as can seen in the call to Currency.create() 

But that multiplying 100 kr with 0.5 gives 0 kr (or 100 kr I think it gives now actually) I think is a bug.
I think the * operator could be coded so that it could handle fractions better. Even when the scale is 0

Anyway I have coded around this issue ... so I am fine.

**Comment by bsutton** [comment]
I'm going to close this one out as I don't think it's a bug.
The package is designed to do fixed scale maths and other is no way (that I'm aware of) of determining the scale of the double.

For the moment I'm going to handle this as a documentation issue and make a note of the issue and the solution which is to first convert the double to a fixed precision and then do the multiplication.
